@echo off
title AerisMP Launcher Build
echo Cleaning previous build...
if exist ".next" rmdir /s /q ".next"
echo Building launcher...
bun tauri build

echo.
echo Build completed! Launching installer...
start "" "src-tauri\target\release\bundle\msi\AerisMP Launcher_1.0.0_x64_en-US.msi"
timeout /t 12
echo Launchers Completed installing...
pause